// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendingMachineApp.Models;

#nullable disable

namespace VendingMachineApp.Migrations
{
    [DbContext(typeof(VendingMachineContext))]
    [Migration("20260228013357_UpdateTransactionSchema")]
    partial class UpdateTransactionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vendingmachine")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendingMachineApp.Models.BalanceHistory", b =>
                {
                    b.Property<int>("IdBalanceHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBalanceHistory"));

                    b.Property<decimal>("CreditBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DebitBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBalanceHistory");

                    b.HasIndex("IdUser");

                    b.ToTable("BalanceHistories", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProduct");

                    b.ToTable("Products", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.SmptpEmail", b =>
                {
                    b.Property<int>("IdSmtp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSmtp"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdSmtp");

                    b.ToTable("SmtpEmails", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.TransactionDetail", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetail"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdTransaction")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDetail");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdTransaction");

                    b.ToTable("TransactionDetails", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserBalance", b =>
                {
                    b.Property<int>("IdUserBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUserBalance"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUserBalance");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("UserBalances", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserLogin", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUser");

                    b.ToTable("UserLogins", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserTransaction", b =>
                {
                    b.Property<int>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransaction"));

                    b.Property<decimal?>("BalanceAfterTransaction")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.Property<string>("TrxCode")
                        .HasColumnType("text");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdUser");

                    b.ToTable("UserTransactions", "vendingmachine");
                });

            modelBuilder.Entity("VendingMachineApp.Models.BalanceHistory", b =>
                {
                    b.HasOne("VendingMachineApp.Models.UserLogin", "User")
                        .WithMany("BalanceHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VendingMachineApp.Models.TransactionDetail", b =>
                {
                    b.HasOne("VendingMachineApp.Models.Product", "Product")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("IdProduct");

                    b.HasOne("VendingMachineApp.Models.UserTransaction", "UserTransaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("IdTransaction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserTransaction");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserBalance", b =>
                {
                    b.HasOne("VendingMachineApp.Models.UserLogin", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("VendingMachineApp.Models.UserBalance", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserTransaction", b =>
                {
                    b.HasOne("VendingMachineApp.Models.UserLogin", "User")
                        .WithMany("UserTransactions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VendingMachineApp.Models.Product", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserLogin", b =>
                {
                    b.Navigation("BalanceHistories");

                    b.Navigation("UserBalance");

                    b.Navigation("UserTransactions");
                });

            modelBuilder.Entity("VendingMachineApp.Models.UserTransaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
